---
  title: "Beautiful Photographs MCA Analysis"
  author: "Omar Lizardo"
  date: "`r Sys.Date()`"
---

# Setup
```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
    library(conflicted)
    library(here)
    library(dplyr)
    library(tidyr)
    library(ggplot2)
    library(sjPlot)
    library(haven)
    library(patchwork)
    library(factoextra)
    library(FactoMineR)
    library(ggrepel)
    library(patchwork)
    conflicts_prefer(dplyr::filter)
    conflicts_prefer(dplyr::select)
    conflicts_prefer(dplyr::summarize)
```


```{r Getting and Recoding Data}
    dat <- read_dta(here("cultdat.dta")) |> 
    mutate(race = factor(race)) |>  
    mutate(age = 
        case_when(
            age2 >= 17 & age2 <= 21 ~ "Age (17-21)",
            age2 >= 22 & age2 <= 26 ~ "Age (22-28)",
            age2 >= 29 & age2 <= 35 ~ "Age (29-35)",
            age2 >= 36 & age2 <= 42 ~ "Age (36-42)",
            age2 >= 43 & age2 <= 49 ~ "Age (43-49)",
            age2 >= 50 & age2 <= 59 ~ "Age (50-59)",
            age2 >= 60 & age2 <= 69 ~ "Age (60-69)",
            age2 >= 70 ~ "Age (70+)"
        )
    ) |> 
    mutate(age = factor(age)) |> 
    mutate(educ = 
        case_when(
            educ == 1 ~ "Less than High School",
            educ == 2 ~ "Less than High School",
            educ == 3 ~ "High School",
            educ == 4 ~ "Some College",
            educ == 5 ~ "Some College",
            educ == 6 ~ "College Degree",
            educ == 7 ~ "Prof./Graduate Degree"
        )
    ) |> 
    mutate(parented = 
        case_when(
            parented == 1 ~ "Less than High School",
            parented == 2 ~ "Less than High School",
            parented == 3 ~ "High School",
            parented == 4 ~ "Some College",
            parented == 5 ~ "Some College",
            parented == 6 ~ "College Degree",
            parented == 7 ~ "Prof./Graduate Degree"
        )
    ) |> 
    mutate(educ = factor(educ), parented = factor(parented)) |>
    rename(par.ed = parented) |> 
    mutate(across(social:economic, as.numeric)) |> 
    mutate(urban_rural =
        case_when(
            urban_rural < 3 ~ "Small Town",
            urban_rural > 2 & urban_rural < 5 ~ "Midsized Town",
            urban_rural > 4 ~ "Big City"
        )
    ) |> 
    mutate(urban_rural = factor(urban_rural)) |> 
    mutate(child_arts =
        case_when(
            child_arts < 3 ~ "Low Exposure to Arts as Child",
            child_arts > 2 & child_arts < 6 ~ "Moderate Exposure to Arts as Child",
            child_arts > 5 ~ "High Exposure to Arts as Child"
        )
    ) |> 
    mutate(child_arts = factor(child_arts)) |> 
    mutate(polviews = 
        case_when(
            poli <= 2.5 ~ "Liberal",
            poli >= 5.5 ~ "Conservative",
            poli > 2.5 & poli < 5.5 ~ "Moderate"
        )
    ) |> 
    mutate(socpol = 
        case_when(
            social <= 2 ~ "Soc. Lib.",
            social >= 6 ~ "Soc. Con.",
            social > 2 & social < 6 ~ "Soc. Mod."
        )
    ) |> 
    mutate(econpol = 
        case_when(
            economic <= 2 ~ "Econ. Lib.",
            economic >= 6 ~ "Econ. Con.",
            economic > 2 & economic < 6 ~ "Econ. Mod."
        )
    ) |> 
    mutate(polviews = factor(polviews)) |> 
    mutate(socpol = factor(socpol)) |> 
    mutate(econpol = factor(econpol)) |> 
    mutate(gender = factor(gender, labels = c("Woman", "Man", "Nonbinary/Other"))) |> 
    rowwise() |> 
        mutate(var.photo = var(c_across(landscape:snake))) |> 
    ungroup() |> 
    mutate(across(landscape:snake, ~factor(., labels = c("Be", "In", "Me", "Ug")))) |> 
    filter(!is.na(var.photo)) |> 
    select(c("age", "educ", "par.ed", "socpol", "econpol", "gender", "child_arts", "urban_rural", "var.photo"), landscape:snake) |> 
    data.frame() |> 
    na.omit()
```

```{r MCA Analysis}
    sups <- which(dat$var.photo <= quantile(dat$var.photo, probs = 0.05))
    mca.dat <- dat[, c(1:8, 10:29)]
    mca.res <- MCA(mca.dat, 
        graph = FALSE, ind.sup = sups, quali.sup = c(1:8))
    col.names <- c("Dim.1", "Dim.2", "Dim.3", "Dim.4", "Dim.5")
    colnames(mca.res$ind$coord) <- col.names
    colnames(mca.res$ind.sup$coord) <- col.names
    colnames(mca.res$quali.sup$coord) <- col.names
```

```{r Cloud of Categories Plot}
    contrib <- log(mca.res$var$contrib[, 1] + mca.res$var$contrib[, 2])
    contrib <- contrib/max(contrib)
    cat.dat <-data.frame(mca.res$var$coord) |> 
        mutate(labels = rownames(mca.res$var$coord)) |> 
        mutate(judgment = 
                case_when(
                    str_detect(labels, "_Be") ~ "Beautiful",
                    str_detect(labels, "_In") ~ "Interesting",
                    str_detect(labels, "_Me") ~ "Meaningless",
                    str_detect(labels, "_Ug") ~ "Ugly",
                )) 
    p <- ggplot(cat.dat, aes(x = Dim.1, y = Dim.2, color = judgment, label = labels))
    p <- p + geom_vline(xintercept = 0, color = "gray", linewidth = 1)
    p <- p + geom_hline(yintercept = 0, color = "gray", linewidth = 1)
    p <- p + geom_label_repel(size = 5.5, max.overlaps = 200, fontface = "bold", alpha = contrib)
    p <- p + theme_minimal() + scale_color_manual(values = c("darkblue", "black", "darkorange", "darkred"))
    p1 <- p + xlim(-3, 4.5) + ylim(-2.25, 2.25) + ggtitle("")
    p1 + theme(legend.position = "top",
                   legend.title = element_blank(),
                   axis.text = element_text(size = 40),
                   axis.title = element_text(size = 40),
                   legend.text = element_text(size = 20)
                   )
    save_plot(here("cat-cloud.png"), height = 50, width = 50) 
```

```{r Cloud of Supplementary Categories Plot}
    library(wesanderson)
    sup.dat <-data.frame(mca.res$quali.sup$coord) |> 
        mutate(labels = rownames(mca.res$quali.sup$coord)) |> 
        mutate(cat.type = c(rep(1, 8), rep(2, 5), rep(3, 5), rep(4, 3), rep(5, 3), rep(6, 3), rep(7, 3), rep(8, 3))) |> 
        mutate(cat.type = factor(cat.type))
    p <- ggplot(sup.dat, aes(x = Dim.1, y = Dim.2, color = cat.type, label = labels))
    p <- p + geom_vline(xintercept = 0, color = "gray", linewidth = 1)
    p <- p + geom_hline(yintercept = 0, color = "gray", linewidth = 1)
    p <- p + geom_label_repel(size = 5.5, max.overlaps = 200, fontface = "bold")
    p <- p + theme_minimal() + scale_color_manual(values = c(wes_palette("BottleRocket1")[1:4], wes_palette("BottleRocket2")[2:5]))
    p2 <- p + xlim(-.6, .6) + ylim(-.3, .3) + ggtitle("")
    p2 + theme(legend.position = "none",
                   legend.title = element_blank(),
                   axis.text = element_text(size = 40),
                   axis.title = element_text(size = 40)
                   )
    save_plot(here("sup-cloud.png"), height = 50, width = 50) 
```

```{r}
    wrap_plots(p1, p2, ncol = 2, nrow = 1, widths = c(2, 1.25)) + plot_annotation(tag_levels = 'a', tag_suffix = ")") & theme(legend.position = "none", text = element_text(size = 30))
    save_plot(here("main.png"), height = 60, width = 80) 
```


```{r Eigenvalue Plot}
    p <- fviz_eig(mca.res, choice = "eigenvalue")
    p <- p + theme(text = element_text(size = 16))
    p + geom_text(label = paste0(round(mca.res$eig[1:10, 2], 1),"%"), vjust=-1, hjust = 0.2,size = 5) + ggtitle("") + ylim(0, 0.2)
    save_plot(here("eig.png"), height = 15, width = 20) 
```

<!-- ```{r Bar plots of category importance}
    dim.res <- dimdesc(mca.res, axes = 1:5)
    make.cat.dat <- function(x) {
        w <- data.frame(x) |> 
        mutate(labels = sub(".*=", "", rownames(x))) |> 
        select(-p.value) |> 
        mutate(judgment = 
                case_when(
                    str_detect(labels, "_Be") ~ "Beautiful",
                    str_detect(labels, "_In") ~ "Interesting",
                    str_detect(labels, "_Me") ~ "Meaningless",
                    str_detect(labels, "_Ug") ~ "Ugly",
                )) 
    rownames(w) <- NULL
    return(w)
    }
    make.bar.plot <- function(w, title = "") {
        p <- ggplot(w, aes(x = Estimate, y = reorder(labels, Estimate), fill = judgment, color = judgment))
        p <- p + geom_col() + theme_minimal()
        p <- p + theme(legend.position = "none", 
              legend.title = element_blank(),
              axis.text = element_text(size = 14, face = "bold"),
              title = element_text(size = 20),
              legend.text = element_text(size = 16)
              ) + labs(x = "", y = "") + ggtitle(title)
        return(p)
    }
    dat1 <- make.cat.dat(dim.res$Dim.1$category) 
    dat1 <- dat1[order(dat1$Estimate), ]
    dat1 <- rbind(tail(dat1, 10), head(dat1, 10))
    dat2 <- make.cat.dat(dim.res$Dim.2$category) 
    dat2 <- dat2[order(dat2$Estimate), ]
    dat2 <- rbind(tail(dat2, 10), head(dat2, 10))
    p3 <- make.bar.plot(dat1, "Dimension 1")
    p4 <- make.bar.plot(dat2, "Dimension 2")
``` -->


<!-- 
```{r Cloud of Variables Plot}
    colnames(mca.res$var$eta2) <- col.names
    cat.dat <-data.frame(mca.res$var$eta2) 
    p <- ggplot(cat.dat, aes(x = Dim.1, y = Dim.2, label = rownames(cat.dat)))
    p <- p + geom_vline(xintercept = 0, color = "lightgray")
    p <- p + geom_hline(yintercept = 0, color = "lightgray")
    p <- p + geom_label_repel(size = 8, max.overlaps = 75)
    p <- p + theme_minimal()
    p + theme(axis.text = element_text(size = 22),
              axis.title = element_text(size = 24)
              )
    save_plot(here("var-cloud.png"), height = 40, width = 50) 
``` -->

<!-- ```{r Regression Models}
    m1 <- glm(Dim.1 ~ age2 + income + educ + child_arts + workarts + polviews + urban_rural, family = "gaussian", data = dat)
    m2 <- glm(Dim.2 ~ age2 + income + educ + child_arts + workarts + polviews + urban_rural, family = "gaussian", data = dat)
    tab_model(m1, m2, 
        file = here("Tabs", "mca-reg.html"), 
        dv.labels = c(
            "Commonplace Subjects <br> Ugly (v. Beautiful)",
            "Non-standard Subjects <br> Beautiful (v. Meaningless)"
            ),
        CSS = list(css.table = 'font-size: 12px;', css.td = 'border-bottom: 0px;'), 
        show.ci = FALSE,  show.se = TRUE, collapse.se = TRUE, p.style = "numeric_stars", show.std = "std2", show.est = FALSE, digits = 3,
        pred.labels = c("Intercept", "Age", "Household Income", "Education", "Child Arts Exp.", "Work in Arts", "Conservative", "Liberal",  "City Size"),
        title = "Table 1. Coefficient estimates of generalized linear models predicting scores on the first and second MCA dimensions."
        )
```
 -->
